### ISSUE TITLE
No named parameter with the name 'overflow'

### ISSUE THREAD

**Issue by theisoft** [manojeeva/jumping_bottom_nav_bar#3]
../../../../.pub-cache/hosted/pub.dartlang.org/jumping_bottom_nav_bar-0.0.4/lib/src/tab_bar.dart:147:7: Error: No named parameter with the name 'overflow'.
      overflow: Overflow.visible,

**Comment by manojeeva** [comment]
Thanks for reporting.
Can you describe more about the issue?
How did you try? what was the flow?

**Comment by theisoft** [comment]
This only happens when I try to compile it in iOS.
