### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by theisoft** [manojeeva/jumping_bottom_nav_bar#4]
Is there an option to add badge? for example I want to show user the number of unread notifs or even just a red dot at the upper right of the icon?

**Comment by manojeeva** [comment]
Hey, @theisoft Thanks for Requesting a new feature.
I've updated the package to v0.1.0.
Now it supports custom widget as tab item and supports background color for the tab bar.
Please upgrade to the latest version to use new features.
